### ISSUE TITLE
Login problems (url format & key error)

### ISSUE THREAD

**Issue by Roboe** [Perflyst/OpenUntis#2]
Hi!

Firstly, thank you so much for this client and its inclusion in F-Droid. [My school](https://rcsmm.eu) implementing this shitty, proprietary software has drove me crazy from the begining, since I don't want to install a closed-source, untrusted app and the _responsive_ web layout is just unuseable.

I'm trying to login into my school's WebUntis at https://mese.webuntis.com/WebUntis/?school=RCSMM. I've tried multiple URLs in the Server URL field, none of it worked. It keeps telling me "Invalid URL!".

Which URL should I put there?

**Comment by curtisy1** [comment]
@Roboe, try using only mese.webuntis.com and setting the school's name in the school name field. That's how it worked for me on first try, maybe it helps .

**Comment by Perflyst** [comment]
@curtisy1 correct!

Here is a demo account for testing:
Server URL: demo.webuntis.com
School name: demomobile
Username: hero
Key: EL4YJQXIPD3ZSG7U

**Comment by Roboe** [comment]
Thank you, @curtisy1. I thought the `https://` was necessary (TLS is important, I wanted to be sure).

Unfortunately it doesn't work neither, this time it brings a "Wrong username or key!" error below the password field. I'm sure the login-password pair is well written —it is working in a web browser.

@Perflyst The demo server works just fine. Could it be an issue with the `mese` subdomain? Installation could be customized or something.

**Comment by curtisy1** [comment]
@Roboe I think the key doesn't refer to the password itself, rather you need to generate a key from within untis itself. The easiest way would be to login via browser, then go to profile in the top right corner. From there, navigate to the tab right next to General (don't know what it's called in English unfortunately) and you should see "access through untis mobile". If you click on the show button there, you get a QR code you can scan for simplicity, or see the key written down. This is the key you need to input in the app itself.

**Comment by Roboe** [comment]
A token! They call it a key in the Web interface ("clave" in Spanish, which is a word used here for user passwords as well…)

It's working, no issues so far. Thank you so much for the help! 🤗

I think some in-app explanation to get the token/key thingy will come handy. Should I open a new issue?

I'll contribute back an Spanish translation, BTW

**Comment by Perflyst** [comment]
Good to know it works. Spanish translation would be great.

You dont need to open an extra issue for that, I will reference the commit to this issue. Thank you!
