### ISSUE TITLE
Server URL is invalid according to the app

### ISSUE THREAD

**Issue by tom-rade** [Perflyst/OpenUntis#23]
webuntis.stp.bsb.stadt.hamburg.de is what the server is when scanning my QR Code.

QR Code contents: www.untis.at/UntisMobile.php?server=webuntis.stp.bsb.stadt.hamburg.de&school=HH[4digits censored]

In the app it says the server URL webuntis.stp.bsb.stadt.hamburg.de is invalid.

**Comment by Perflyst** [comment]
Which url do you use to access untis via webuntis? There is no DNS A or AAAA record for `webuntis.stp.bsb.stadt.hamburg.de`.

**Comment by tom-rade** [comment]
Has been solved, problem on my end.
