### ISSUE TITLE
[Feature-Request] Automatically mute the smartphone when a lesson starts

### ISSUE THREAD

**Issue by Preisschild** [Perflyst/OpenUntis#29]
This would be a nice to have feature.

IIRC the official app has this feature too.

**Comment by SimonIT** [comment]
I began to implement it, but I got currently no time for it. If you want help or see my progress look at my branch [dnd](https://github.com/SimonIT/OpenUntis/tree/dnd). The missing feature is to unmute after every lesson (the last one is the complicated).

**Comment by Preisschild** [comment]
Great job! Hope F-Droid picks the new release up soon.
